name: 🚀 Feature Request
description: Suggest a new feature or enhancement
title: "[Feature Request]: "
labels: ["enhancement"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please search existing issues first to avoid duplicates.

  - type: textarea
    id: problem
    attributes:
      label: 🎯 Problem Statement
      description: What problem does this feature solve?
      placeholder: |
        Currently, it's difficult to...
        This would help me...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: 💡 Proposed Solution
      description: Describe your proposed feature in detail
      placeholder: |
        I propose we add...
        This would work by...
        The user interface would...
    validations:
      required: true

  - type: textarea
    id: use-cases
    attributes:
      label: 📈 Use Cases & Examples
      description: Provide specific examples of how this feature would be used
      placeholder: |
        Use case 1: A trader wants to...
        Use case 2: A developer needs to...
        Example scenario: When building an agent for...

  - type: dropdown
    id: priority
    attributes:
      label: 📊 Priority
      description: How important is this feature to you and the community?
      options:
        - Critical - Blocking important workflows
        - High - Would significantly improve experience
        - Medium - Nice improvement to have
        - Low - Minor quality of life improvement
    validations:
      required: true

  - type: textarea
    id: architecture
    attributes:
      label: 🏗️ Code Architecture
      description: Explain the technical architecture and implementation approach for this feature
      placeholder: |
        Architecture overview:
        - Where this feature fits in the codebase structure
        - New files/modules that would be created
        - Existing components that would be modified

        Technical approach:
        - Core classes/interfaces needed
        - Data flow and state management
        - Integration points with existing systems

        Dependencies:
        - New libraries or frameworks required
        - Breaking changes to existing APIs
        - Database schema changes (if applicable)
    validations:
      required: true

  - type: textarea
    id: mockups
    attributes:
      label: 🎨 Mockups/References
      description: Visual mockups, reference implementations, or similar features in other projects
      placeholder: |
        Link to mockups, wireframes, or screenshots...
        Similar feature in other projects: https://...
        Reference implementations: https://...

  - type: checkboxes
    id: checklist
    attributes:
      label: ✅ Pre-submission Checklist
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: I have clearly described the problem this feature solves
          required: true
        - label: I have provided specific use cases and examples
          required: true
        - label: I will wait for the Vibekit team to approve this issue before continuing to implementation
          required: true
